// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nodaq-landing/NodaqLanding.tsx": () => import("../components/mockups/nodaq-landing/NodaqLanding.tsx"),
  "./components/mockups/nodaq-landing/NodaqLandingDarkGlass.tsx": () => import("../components/mockups/nodaq-landing/NodaqLandingDarkGlass.tsx"),
  "./components/mockups/nodaq-landing/NodaqLandingEarthy.tsx": () => import("../components/mockups/nodaq-landing/NodaqLandingEarthy.tsx"),
  "./components/mockups/nodaq-landing/NodaqLandingNeoBrutalist.tsx": () => import("../components/mockups/nodaq-landing/NodaqLandingNeoBrutalist.tsx")
};
